<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>archer-apphost-1c0a</UserSecretsId>
    <NoWarn>$(NoWarn);ASPIREHOSTINGPYTHON001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Archer.Tui\Archer.Tui.csproj" />
    <ProjectReference Include="..\Archer.Cli\Archer.Cli.csproj" />
  </ItemGroup>

</Project>
